version: "3"

services:
  app:
    image: prithuadhikary/docker-demo:1.2
    ports:
      - 80:8080
    networks:
      - backend
      - frontend
    environment:
      SPRING_PROFILES_ACTIVE: devcloud
    deploy:
      replicas: 3

  db:
    image: postgres:13.4-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: opabs
      POSTGRES_USER: opabs
      POSTGRES_PASSWORD: Jotujanta12#
    deploy:
      replicas: 1

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay

volumes:
  db-data: